### ISSUE TITLE
יש אפשרות לקבל הסבר בעברית על התבנית של השטיח?

### ISSUE THREAD

**Issue by dolev146** [cpp-exercises-5782/mat-a#1]
לא ברור לי מה התבנית של השטיח , אם אפשר לקבל הסבר בעברית 

אם אפשר לקבל עוד דוגמאות בבקשה  , למה זה קשור למספרים זוגיים ? אי זוגיים ? מתי אני שם כל סימן לא הבנתי 
למשל עבור הקלטים הבאים 

( 1 , 1 , @ , -  )
( 2 , 1 , @ , -  )
( 3, 1 , @ , -  )
( 50 , 1 , @ , -  )
( 1 , 2 , @ , -  )
( 1 , 3, @ , -  )
( 1 , 5 , @ , -  )
( 1 , 90 , @ , -  )
( 2, 2 , @ , -  )
( 3 , 3 , @ , -  )
( 4 , 4 , @ , -  )
( 5 , 5, @ , -  )
( 6 , 6 , @ , -  )
( 7 , 7 , @ , -  )
( 8 , 8 , @ , -  )
( 9 , 9 , @ , -  )

הבנתי שאם הקלט הוא למשל
( width , height , @ , - }
אז אני צריך לעשות מטריצה 
width * height 
אבל מה הולך שם בפנים מה החוקיות לא ברור 

תודה רבה על זמנך
 
דולב

**Comment by talzich** [comment]
היי דולב, מקווה שהסתדרת עד עכשיו.
בכל אופן, הרעיון הוא ליצור טבעות שמתחילות בסימן הראשון, ממשיכות בשני וחוזרות לראשון וכן הלאה, כל עוד גודל השטיח מאפשר זאת.
במשימה הנוכחית המטרה היא רק לכתוב בדיקות עבור התנהגות זו, ולא את המימוש עצמו.
בהצלחה!
